language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
virtualenv:
  system_site_packages: true
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:  pip install tox-travis
script: tox